exclude: ^(poetry.lock|.idea/)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.2"
    hooks:
      - id: ruff-format
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        description: Strip output from Jupyter notebooks
        files: \.ipynb$
